name: Build and Deploy

on:
  push:
    branches:
      - main  # Change to your main branch name if needed

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04  # Specify the Ubuntu version

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Specify the Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy
        run: npm run deploy
